In [ ]:
! pip install streamlit -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 15.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.4/196.4 kB 14.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 32.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 kB 9.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 7.1 MB/s eta 0:00:00

In [ ]:
!wget -q -O - ipv4.icanhazip.com

34.80.243.166

In [74]:
!streamlit run app.py & npx localtunnel --port 8501

[..................] \ fetchMetadata: sill resolveWithNewModule localtunnel@2.0
Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.


  You can now view your Streamlit app in your browser.

  Network URL: http://172.28.0.12:8501
  External URL: http://34.80.243.166:8501

npx: installed 22 in 3.047s
your url is: https://big-moles-raise.loca.lt
  Stopping...
^C

# 1. Kindly run the first three codes.
# 2. After running the second code, we will receive a passcode.
# 3. After running the third code, we will get an url, click on the url, the url will take us to a streamlit webpage, enter the provided passcode and launch the streamlit.
# 4. The Dashboard will be visible.

In [ ]:
my_df = pd.read_csv('/content/Population data.csv')
my_df

,country,country_code,id,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Afghanistan,AFG,1,31541209,32716210,33753499,34636207,35643418,36686784,37769499,38972230,40099462,41128771
1,Albania,ALB,2,2895092,2889104,2880703,2876101,2873457,2866376,2854191,2837849,2811666,2777689
2,Arab World,ARB,3,389131555,397922915,406501999,415077960,423664839,432545676,441467739,449228296,456520777,464684914
3,United Arab Emirates,ARE,4,8751847,8835951,8916899,8994263,9068296,9140169,9211657,9287289,9365145,9441129
4,Argentina,ARG,5,42202935,42669500,43131966,43590368,44044811,44494502,44938712,45376763,45808747,46234830
5,Australia,AUS,6,23128129,23475686,23815995,24190907,24592588,24963258,25334826,25649248,25685412,26005540
6,Belgium,BEL,7,11159407,11209057,11274196,11331422,11375158,11427054,11488980,11538604,11586195,11685814
7,Bangladesh,BGD,8,154030139,155961299,157830000,159784568,161793964,163683958,165516222,167420951,169356251,171186372
8,Brazil,BRA,9,201721767,203459650,205188205,206859578,208504960,210166592,211782878,213196304,214326223,215313498
9,Canada,CAN,10,35082954,35437435,35702908,36109487,36545236,37065084,37601230,38007166,38226498,38929902
10,Chile,CHL,11,17509925,17687108,17870124,18083879,18368577,18701450,19039485,19300315,19493184,19603733
11,China,CHN,12,1363240000,1371860000,1379860000,1387790000,1396215000,1402760000,1407745000,1411100000,1412360000,1412175000
12,Germany,DEU,13,80645605,80982500,81686611,82348669,82657002,82905782,83092962,83160871,83196078,83797985
13,Denmark,DNK,14,5614932,5643475,5683483,5728010,5764980,5793636,5814422,5831404,5856733,5903037
14,"Egypt, Arab Rep.",EGY,15,93377890,95592324,97723799,99784030,101789386,103740765,105618671,107465134,109262178,110990103
15,Spain,ESP,16,46620045,46480882,46444832,46484062,46593236,46797754,47134837,47365655,47415794,47778340
16,Ethiopia,ETH,17,97084366,99746766,102471895,105293228,108197950,111129438,114120594,117190911,120283026,123379924
17,Finland,FIN,18,5438972,5461512,5479531,5495303,5508214,5515525,5521606,5529543,5541017,5556106
18,France,FRA,19,66002289,66312067,66548272,66724104,66918020,67158348,67388001,67571107,67764304,67971311
19,United Kingdom,GBR,20,64128273,64602298,65116219,65611593,66058859,66460344,66836327,67081234,67026292,66971395
20,Ghana,GHA,21,27525597,28196358,28870939,29554303,30222262,30870641,31522290,32180401,32833031,33475870
21,Greece,GRC,22,10965211,10892413,10820883,10775971,10754679,10732882,10721582,10698599,10569207,10426919
22,Greenland,GRL,23,56483,56295,56114,56186,56172,56023,56225,56367,56653,56661
23,Croatia,HRV,24,4255689,4238389,4203604,4174349,4124531,4087843,4065253,4047680,3879000,3855600
24,Hungary,HUN,25,9893082,9866468,9843028,9814023,9787966,9775564,9771141,9750149,9709891,9643048
25,India,IND,26,1291132063,1307246509,1322866505,1338636340,1354195680,1369003306,1383112050,1396387127,1407563842,1417173173
26,"Iran, Islamic Rep.",IRN,27,78458928,79961672,81790841,83306231,84505076,85617562,86564202,87290193,87923432,88550570
27,Iraq,IRQ,28,35481800,36746488,37757813,38697943,39621162,40590700,41563520,42556984,43533592,44496122
28,Italy,ITA,29,60233948,60789140,60730582,60627498,60536709,60421760,59729081,59438851,59133173,58940425
29,Japan,JPN,30,127445000,127276000,127141000,127076000,126972000,126811000,126633000,126261000,125681593,125124989
30,Kuwait,KWT,31,3646518,3761584,3908743,4048085,4124904,4317185,4441100,4360444,4250114,4268873
31,Mexico,MEX,32,117290686,118755887,120149897,121519221,122839258,124013861,125085311,125998302,126705138,127504125
32,Malaysia,MYS,33,30134807,30606459,31068833,31526418,31975806,32399271,32804020,33199993,33573874,33938221
33,Netherlands,NLD,34,16804432,16865008,16939923,17030314,17131296,17231624,17344874,17441500,17533044,17700982
34,New Zealand,NZL,35,4442100,4516500,4609400,4714100,4813600,4900600,4979200,5090200,5111400,5124100
35,Oman,OMN,36,3816680,4009267,4191776,4398070,4541854,4601157,4602768,4543399,4520471,4576298
36,Pakistan,PAK,37,205337562,208251628,210969298,213524840,216379655,219731479,223293280,227196741,231402117,235824862
37,Poland,POL,38,38040196,38011735,37986412,37970087,37974826,37974750,37965475,37899070,37747124,36821749
38,"Korea, Dem. People's Rep.",PRK,39,25001819,25126131,25258015,25389611,25516321,25638149,25755441,25867467,25971909,26069416
39,Qatar,QAT,40,2035501,2214465,2414573,2595166,2711755,2766732,2807235,2760385,2688235,2695122
40,Russian Federation,RUS,41,143506995,143819667,144096870,144342397,144496739,144477859,144406261,144073139,144130482,144236933
41,Thailand,THA,42,69578602,69960943,70294397,70607037,70898202,71127802,71307763,71475664,71601103,71697030
42,Uruguay,URY,43,3381180,3391662,3402818,3413766,3422200,3427042,3428409,3429086,3426260,3422794
43,United States,USA,44,316059947,318386329,320738994,323071755,325122128,326838199,328329953,331511512,332031554,333287557
44,South Africa,ZAF,45,53873616,54729551,55876504,56422274,56641209,57339635,58087055,58801927,59392255,59893885
45,Zimbabwe,ZWE,46,13555422,13855753,14154937,14452704,14751101,15052184,15354608,15669666,15993524,16320537
46,European Union,EUU,47,442496175,443601373,444570054,445515422,446215182,447001100,447367191,447692315,447178112,447370510
47,Ireland,IRL,48,4623816,4657740,4701957,4755335,4807388,4867316,4934340,4985382,5033164,5127170
48,Jordan,JOR,49,7694814,8658026,9494246,9964656,10215381,10459865,10698683,10928721,11148278,11285869
49,Kenya,KEN,50,44792368,45831863,46851488,47894670,48948137,49953304,50951450,51985780,53005614,54027487

In [ ]:
# Reshape the DataFrame
df_reshaped = pd.melt(my_df, id_vars=['country', 'country_code', 'id'], var_name='year', value_name='population')

# Convert 'year' column values to integers
df_reshaped['country'] = df_reshaped['country'].astype(str)
df_reshaped['year'] = df_reshaped['year'].astype(int)

# Replace commas in the 'population' column and convert to integers
df_reshaped['population'] = df_reshaped['population'].replace(',', '', regex=True).astype(int)

df_reshaped

                  country country_code  id  year  population
0             Afghanistan          AFG   1  2013    31541209
1                 Albania          ALB   2  2013     2895092
2              Arab World          ARB   3  2013   389131555
3    United Arab Emirates          ARE   4  2013     8751847
4               Argentina          ARG   5  2013    42202935
..                    ...          ...  ..   ...         ...
495              Zimbabwe          ZWE  46  2022    16320537
496        European Union          EUU  47  2022   447370510
497               Ireland          IRL  48  2022     5127170
498                Jordan          JOR  49  2022    11285869
499                 Kenya          KEN  50  2022    54027487

[500 rows x 5 columns]

In [ ]:
# Save reshaped data to CSV
df_reshaped.to_csv('population-data-2013-2022.csv')

In [ ]:
df = pd.read_csv("/content/population-data-2013-2022.csv")
df

     Unnamed: 0               country country_code  id  year  population
0             0           Afghanistan          AFG   1  2013    31541209
1             1               Albania          ALB   2  2013     2895092
2             2            Arab World          ARB   3  2013   389131555
3             3  United Arab Emirates          ARE   4  2013     8751847
4             4             Argentina          ARG   5  2013    42202935
..          ...                   ...          ...  ..   ...         ...
495         495              Zimbabwe          ZWE  46  2022    16320537
496         496        European Union          EUU  47  2022   447370510
497         497               Ireland          IRL  48  2022     5127170
498         498                Jordan          JOR  49  2022    11285869
499         499                 Kenya          KEN  50  2022    54027487

[500 rows x 6 columns]

In [ ]:
# Subset dataframe by year
selected_year = 2022
df_selected_year = df_reshaped[df_reshaped.year == selected_year]
df_selected_year

                       country country_code  id  year  population
450                Afghanistan          AFG   1  2022    41128771
451                    Albania          ALB   2  2022     2777689
452                 Arab World          ARB   3  2022   464684914
453       United Arab Emirates          ARE   4  2022     9441129
454                  Argentina          ARG   5  2022    46234830
455                  Australia          AUS   6  2022    26005540
456                    Belgium          BEL   7  2022    11685814
457                 Bangladesh          BGD   8  2022   171186372
458                     Brazil          BRA   9  2022   215313498
459                     Canada          CAN  10  2022    38929902
460                      Chile          CHL  11  2022    19603733
461                      China          CHN  12  2022  1412175000
462                    Germany          DEU  13  2022    83797985
463                    Denmark          DNK  14  2022     5903037
464           Egypt, Arab Rep.          EGY  15  2022   110990103
465                      Spain          ESP  16  2022    47778340
466                   Ethiopia          ETH  17  2022   123379924
467                    Finland          FIN  18  2022     5556106
468                     France          FRA  19  2022    67971311
469             United Kingdom          GBR  20  2022    66971395
470                      Ghana          GHA  21  2022    33475870
471                     Greece          GRC  22  2022    10426919
472                  Greenland          GRL  23  2022       56661
473                    Croatia          HRV  24  2022     3855600
474                    Hungary          HUN  25  2022     9643048
475                      India          IND  26  2022  1417173173
476         Iran, Islamic Rep.          IRN  27  2022    88550570
477                       Iraq          IRQ  28  2022    44496122
478                      Italy          ITA  29  2022    58940425
479                      Japan          JPN  30  2022   125124989
480                     Kuwait          KWT  31  2022     4268873
481                     Mexico          MEX  32  2022   127504125
482                   Malaysia          MYS  33  2022    33938221
483                Netherlands          NLD  34  2022    17700982
484                New Zealand          NZL  35  2022     5124100
485                       Oman          OMN  36  2022     4576298
486                   Pakistan          PAK  37  2022   235824862
487                     Poland          POL  38  2022    36821749
488  Korea, Dem. People's Rep.          PRK  39  2022    26069416
489                      Qatar          QAT  40  2022     2695122
490         Russian Federation          RUS  41  2022   144236933
491                   Thailand          THA  42  2022    71697030
492                    Uruguay          URY  43  2022     3422794
493              United States          USA  44  2022   333287557
494               South Africa          ZAF  45  2022    59893885
495                   Zimbabwe          ZWE  46  2022    16320537
496             European Union          EUU  47  2022   447370510
497                    Ireland          IRL  48  2022     5127170
498                     Jordan          JOR  49  2022    11285869
499                      Kenya          KEN  50  2022    54027487

In [ ]:
# Sort by year
df_selected_year_sorted = df_selected_year.sort_values(by="population", ascending=False)
df_selected_year_sorted

                       country country_code  id  year  population
475                      India          IND  26  2022  1417173173
461                      China          CHN  12  2022  1412175000
452                 Arab World          ARB   3  2022   464684914
496             European Union          EUU  47  2022   447370510
493              United States          USA  44  2022   333287557
486                   Pakistan          PAK  37  2022   235824862
458                     Brazil          BRA   9  2022   215313498
457                 Bangladesh          BGD   8  2022   171186372
490         Russian Federation          RUS  41  2022   144236933
481                     Mexico          MEX  32  2022   127504125
479                      Japan          JPN  30  2022   125124989
466                   Ethiopia          ETH  17  2022   123379924
464           Egypt, Arab Rep.          EGY  15  2022   110990103
476         Iran, Islamic Rep.          IRN  27  2022    88550570
462                    Germany          DEU  13  2022    83797985
491                   Thailand          THA  42  2022    71697030
468                     France          FRA  19  2022    67971311
469             United Kingdom          GBR  20  2022    66971395
494               South Africa          ZAF  45  2022    59893885
478                      Italy          ITA  29  2022    58940425
499                      Kenya          KEN  50  2022    54027487
465                      Spain          ESP  16  2022    47778340
454                  Argentina          ARG   5  2022    46234830
477                       Iraq          IRQ  28  2022    44496122
450                Afghanistan          AFG   1  2022    41128771
459                     Canada          CAN  10  2022    38929902
487                     Poland          POL  38  2022    36821749
482                   Malaysia          MYS  33  2022    33938221
470                      Ghana          GHA  21  2022    33475870
488  Korea, Dem. People's Rep.          PRK  39  2022    26069416
455                  Australia          AUS   6  2022    26005540
460                      Chile          CHL  11  2022    19603733
483                Netherlands          NLD  34  2022    17700982
495                   Zimbabwe          ZWE  46  2022    16320537
456                    Belgium          BEL   7  2022    11685814
498                     Jordan          JOR  49  2022    11285869
471                     Greece          GRC  22  2022    10426919
474                    Hungary          HUN  25  2022     9643048
453       United Arab Emirates          ARE   4  2022     9441129
463                    Denmark          DNK  14  2022     5903037
467                    Finland          FIN  18  2022     5556106
497                    Ireland          IRL  48  2022     5127170
484                New Zealand          NZL  35  2022     5124100
485                       Oman          OMN  36  2022     4576298
480                     Kuwait          KWT  31  2022     4268873
473                    Croatia          HRV  24  2022     3855600
492                    Uruguay          URY  43  2022     3422794
451                    Albania          ALB   2  2022     2777689
489                      Qatar          QAT  40  2022     2695122
472                  Greenland          GRL  23  2022       56661

In [ ]:
# Calculate population difference between selected and previous year
def calculate_population_difference(input_df, input_year):
  selected_year_data = input_df[input_df['year'] == input_year].reset_index()
  previous_year_data = input_df[input_df['year'] == input_year - 1].reset_index()
  selected_year_data['population_difference'] = selected_year_data.population.sub(previous_year_data.population, fill_value=0)
  selected_year_data['population_difference_absolute'] = abs(selected_year_data['population_difference'])
  return pd.concat([selected_year_data.country, selected_year_data.id, selected_year_data.population, selected_year_data.population_difference, selected_year_data.population_difference_absolute], axis=1).sort_values(by="population_difference", ascending=False)

df_population_difference_sorted = calculate_population_difference(df_reshaped, selected_year)
df_population_difference_sorted

,country,id,population,population_difference,population_difference_absolute
25,India,26,1417173173,9609331,9609331
2,Arab World,3,464684914,8164137,8164137
36,Pakistan,37,235824862,4422745,4422745
16,Ethiopia,17,123379924,3096898,3096898
7,Bangladesh,8,171186372,1830121,1830121
14,"Egypt, Arab Rep.",15,110990103,1727925,1727925
43,United States,44,333287557,1256003,1256003
0,Afghanistan,1,41128771,1029309,1029309
49,Kenya,50,54027487,1021873,1021873
8,Brazil,9,215313498,987275,987275
27,Iraq,28,44496122,962530,962530
31,Mexico,32,127504125,798987,798987
9,Canada,10,38929902,703404,703404
20,Ghana,21,33475870,642839,642839
26,"Iran, Islamic Rep.",27,88550570,627138,627138
12,Germany,13,83797985,601907,601907
44,South Africa,45,59893885,501630,501630
4,Argentina,5,46234830,426083,426083
32,Malaysia,33,33938221,364347,364347
15,Spain,16,47778340,362546,362546
45,Zimbabwe,46,16320537,327013,327013
5,Australia,6,26005540,320128,320128
18,France,19,67971311,207007,207007
46,European Union,47,447370510,192398,192398
33,Netherlands,34,17700982,167938,167938
48,Jordan,49,11285869,137591,137591
10,Chile,11,19603733,110549,110549
40,Russian Federation,41,144236933,106451,106451
6,Belgium,7,11685814,99619,99619
38,"Korea, Dem. People's Rep.",39,26069416,97507,97507
41,Thailand,42,71697030,95927,95927
47,Ireland,48,5127170,94006,94006
3,United Arab Emirates,4,9441129,75984,75984
35,Oman,36,4576298,55827,55827
13,Denmark,14,5903037,46304,46304
30,Kuwait,31,4268873,18759,18759
17,Finland,18,5556106,15089,15089
34,New Zealand,35,5124100,12700,12700
39,Qatar,40,2695122,6887,6887
22,Greenland,23,56661,8,8
42,Uruguay,43,3422794,-3466,3466
23,Croatia,24,3855600,-23400,23400
1,Albania,2,2777689,-33977,33977
19,United Kingdom,20,66971395,-54897,54897
24,Hungary,25,9643048,-66843,66843
21,Greece,22,10426919,-142288,142288
11,China,12,1412175000,-185000,185000
28,Italy,29,58940425,-192748,192748
29,Japan,30,125124989,-556604,556604
37,Poland,38,36821749,-925375,925375

In [ ]:
# Filter states with population difference > 50000
df_greater_50000 = df_population_difference_sorted[df_population_difference_sorted.population_difference_absolute > 50000]
df_greater_50000

,country,id,population,population_difference,population_difference_absolute
25,India,26,1417173173,9609331,9609331
2,Arab World,3,464684914,8164137,8164137
36,Pakistan,37,235824862,4422745,4422745
16,Ethiopia,17,123379924,3096898,3096898
7,Bangladesh,8,171186372,1830121,1830121
14,"Egypt, Arab Rep.",15,110990103,1727925,1727925
43,United States,44,333287557,1256003,1256003
0,Afghanistan,1,41128771,1029309,1029309
49,Kenya,50,54027487,1021873,1021873
8,Brazil,9,215313498,987275,987275
27,Iraq,28,44496122,962530,962530
31,Mexico,32,127504125,798987,798987
9,Canada,10,38929902,703404,703404
20,Ghana,21,33475870,642839,642839
26,"Iran, Islamic Rep.",27,88550570,627138,627138
12,Germany,13,83797985,601907,601907
44,South Africa,45,59893885,501630,501630
4,Argentina,5,46234830,426083,426083
32,Malaysia,33,33938221,364347,364347
15,Spain,16,47778340,362546,362546
45,Zimbabwe,46,16320537,327013,327013
5,Australia,6,26005540,320128,320128
18,France,19,67971311,207007,207007
46,European Union,47,447370510,192398,192398
33,Netherlands,34,17700982,167938,167938
48,Jordan,49,11285869,137591,137591
10,Chile,11,19603733,110549,110549
40,Russian Federation,41,144236933,106451,106451
6,Belgium,7,11685814,99619,99619
38,"Korea, Dem. People's Rep.",39,26069416,97507,97507
41,Thailand,42,71697030,95927,95927
47,Ireland,48,5127170,94006,94006
3,United Arab Emirates,4,9441129,75984,75984
35,Oman,36,4576298,55827,55827
19,United Kingdom,20,66971395,-54897,54897
24,Hungary,25,9643048,-66843,66843
21,Greece,22,10426919,-142288,142288
11,China,12,1412175000,-185000,185000
28,Italy,29,58940425,-192748,192748
29,Japan,30,125124989,-556604,556604
37,Poland,38,36821749,-925375,925375

In [ ]:
# % of States with population difference > 50000
int((len(df_greater_50000)/df_population_difference_sorted.country.nunique())*100)

82

In [72]:
import altair as alt

alt.themes.enable("dark")

heatmap = alt.Chart(df_reshaped).mark_rect().encode(
        y=alt.Y('year:O', axis=alt.Axis(title="Year", titleFontSize=16, titlePadding=15, titleFontWeight=900, labelAngle=0)),
        x=alt.X('country:O', axis=alt.Axis(title="Countries", titleFontSize=16, titlePadding=15, titleFontWeight=900)),
        color=alt.Color('max(population):Q',
                         legend=alt.Legend(title=" "),
                         scale=alt.Scale(scheme="blueorange")),
        stroke=alt.value('black'),
        strokeWidth=alt.value(0.25),
        #tooltip=[
        #    alt.Tooltip('year:O', title='Year'),
        #    alt.Tooltip('population:Q', title='Population')
        #]
    ).properties(width=900
    #).configure_legend(orient='bottom', titleFontSize=16, labelFontSize=14, titlePadding=0
    #).configure_axisX(labelFontSize=14)
    ).configure_axis(
    labelFontSize=12,
    titleFontSize=12
    )

heatmap

alt.Chart(...)

In [ ]:
import altair as alt
from vega_datasets import data

alt.themes.enable("dark")

country = alt.topo_feature(data.world_110m.url, 'countries')

alt.Chart(country).mark_geoshape().encode(
    color=alt.Color('population:Q', scale=alt.Scale(scheme='blues')),
    stroke=alt.value('#154360')
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(df_selected_year, 'id', list(df_selected_year.columns))
).properties(
    width=500,
    height=300
).project(
    type='equirectangular'
)

alt.Chart(...)

In [ ]:
import plotly.express as px
import pandas as pd

# Assuming you have a 'Country Code' column in your DataFrame, you can use it for mapping
fig = px.choropleth(df_selected_year,
                    locations='country_code',
                    color='population',
                    color_continuous_scale='blues',
                    projection='natural earth',
                    title='Population by Country',
                    labels={'population': 'Population'}
                   )

# Show the figure
fig.show()

In [ ]:
# Create choropleth map
choropleth = px.choropleth(df_selected_year,
                            locations='country_code',
                            color='population',
                            locationmode="ISO-3",
                            color_continuous_scale='blues',
                            range_color=(0, max(df_selected_year['population'])),
                            scope="world",
                            labels={'population': 'Population'}
                           )

# Update layout
choropleth.update_layout(
    template='plotly_dark',
    plot_bgcolor='rgba(0, 0, 0, 0)',
    paper_bgcolor='rgba(0, 0, 0, 0)',
    margin=dict(l=0, r=0, t=0, b=0),
    height=350
)

# Display the choropleth map
choropleth.show()

# Objective:
The overarching aim of our project is to construct a robust and intuitive dashboard that harnesses a comprehensive dataset spanning the population statistics of diverse countries from 2013 to 2022. The dashboard is meticulously designed to furnish users with an interactive interface, allowing them to delve into intricate population trends, make cross-country comparisons, and extract nuanced insights into demographic shifts during the specified time period.

# Analysis:
1. **Dynamic Heat Map Visualization:**
   - At the heart of the dashboard lies a dynamic heat map, offering users the flexibility to visualize and interpret population variations across countries for each year. The incorporation of a color slicer provides users with the liberty to choose a color scale, enhancing the interpretability and depth of the displayed data.

2. **Identification of Highest and Least Populated Countries:**
   - The dashboard enables users to select a specific year using the slicer, dynamically presenting both the highest and least populated countries for the chosen year. This comparative analysis facilitates the identification of demographic outliers and aids in discerning overarching trends.

3. **Insightful Bar Chart Representation:**
   - Complementing the heat map is a sophisticated bar chart that graphically represents the population of all countries. This visualization is instrumental in providing an at-a-glance overview of population distributions, facilitating the identification of countries with noteworthy demographic shifts.

# Inferences & Insights:
1. **Discerning Temporal Population Changes:**
   - The dynamic heat map serves as a powerful tool for discerning temporal changes in population, enabling users to identify growth or decline trends in different countries over the specified time frame. These patterns contribute to a deeper understanding of the multifaceted factors influencing demographic changes.

2. **Facilitating Yearly Comparisons:**
   - The incorporation of a slicer allows users to seamlessly select specific years, fostering yearly comparisons. This feature empowers users to pinpoint countries experiencing significant population growth or decline, thereby aiding in a nuanced exploration of global demographic dynamics.

3. **Identifying Demographic Outliers:**
   - The dynamic display of the highest and least populated countries for each selected year facilitates the identification of demographic outliers. This information is invaluable for policymakers, researchers, and businesses seeking to focus attention on regions with distinctive demographic characteristics.

4. **Holistic Global Demographic Overview:**
   - The bar chart provides a comprehensive snapshot of population distribution across all countries. Users can expeditiously identify countries with the largest and smallest populations, contributing to a holistic understanding of global demographic patterns and their implications.

# Conclusion:
In conclusion, our meticulously crafted dashboard transforms raw population data into a visually compelling and interactively rich platform. This tool empowers users across various domains – from academia to policymaking and business planning – to explore, analyze, and derive meaningful insights from the dynamic and complex tapestry of global population dynamics.

# Acknowledement
The codes have been adopted using ChatGPT and gemini ai. The dataset has been adopted from **https://data.worldbank.org/indicator/SP.POP.TOTL**